theme = "hugo-now-ui"
baseurl = "https://sochigeo2019.netlify.com"
languageCode = "en-us"
title = "SOCHIGEO 2019"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "./public"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Components"
    url = "/components/"
    pre = "<i class='now-ui-icons files_single-copy-04'></i>"
    weight = 1
[[menu.main]]
    name = "Proyecto"
    url = "/landing/"
    pre = "<i class='now-ui-icons education_paper'></i>"
    weight = 1
[[menu.main]]
    name = "Analysis"
    pre = "<i class='now-ui-icons design_bullet-list-67'></i>"
    url = "#"
    weight = 2
    identifier = "Analysis"
[[menu.main]]
    name = "Template"
    pre = "<i class='now-ui-icons files_paper'></i>"
    url = "/template/"
    weight = 1
    parent = "Analysis"
[[menu.main]]
    name = "Estructura"
    pre = "<i class='now-ui-icons ui-1_calendar-60'></i>"
    url = "/Estructura/"
    weight = 2
    parent = "Analysis"
[[menu.main]]
    name = "Tags"
    pre = "<i class='now-ui-icons shopping_tag-content'></i>"
    url = "/tags/"
    weight = 2
    parent = "Analysis"    
[[menu.main]]
    name = "Signup"
    pre = "<i class='now-ui-icons gestures_tap-01'></i>"
    url = "/login/"
    weight = 3
[[menu.main]]
    name = "Profile"
    url = "/profile/"
    pre = "<i class='now-ui-icons users_single-02'></i>"
    weight = 4
    
    
[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/JLManzanaresR"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = ""
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "MIT"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3

[params]
    background = "/img/bg11.jpg"
    tint = "blue"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"


    

